# Generated by Django 5.1.3 on 2024-11-23 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas_app', '0003_remove_perfil_biografia_remove_perfil_foto_perfil_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='valoracion',
            name='fecha',
        ),
        migrations.AddField(
            model_name='valoracion',
            name='valor',
            field=models.IntegerField(default=1),
        ),
    ]
