# Generated by Django 5.1.3 on 2024-11-23 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recetas_app', '0004_remove_valoracion_fecha_valoracion_valor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Perfil',
        ),
    ]
