# Generated by Django 5.1.3 on 2024-11-24 02:20

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas_app', '0007_receta_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receta',
            name='imagen',
        ),
        migrations.CreateModel(
            name='ImagenReceta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='recetas/imagenes/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])])),
                ('receta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='recetas_app.receta')),
            ],
        ),
    ]
