# Generated by Django 5.1.3 on 2024-11-24 02:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas_app', '0008_remove_receta_imagen_imagenreceta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagenreceta',
            name='imagen',
            field=models.ImageField(upload_to='recetas/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])]),
        ),
    ]
