# Generated by Django 5.1.3 on 2024-11-24 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas_app', '0009_alter_imagenreceta_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='receta',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='recetas/'),
        ),
        migrations.DeleteModel(
            name='ImagenReceta',
        ),
    ]
