# Generated by Django 5.1.3 on 2024-11-24 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas_app', '0010_receta_imagen_delete_imagenreceta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receta',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='recetas_imagenes/'),
        ),
    ]
